version: 3
jobs:
  build:
    docker:
      - image: wodby/php:7.1
    steps:
      - checkout
      - run:
          name: debug fs
          command: ls -lah && echo $PWD
      - run:
          name: Composer install
          command: composer install --prefer-dist --working-dir=build
      - run:
          name: Phing build
          command: build/bin/phing -f build/phing/build.xml build
  test:
    docker:
      - image: integratedexperts/circleci2-builder
    steps:
      - run:
          name: Phing test
          command: build/bin/phing -f build/phing/build.xml run-tests
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
