version: 2
jobs:
  build:
    steps:
      - run:
          name: Composer install
          command: composer install --prefer-dist --working-dir=build
      - run:
          name: Phing build
          command: build/bin/phing -f build/phing/build.xml build
  test:
    steps:
      - run:
          name: Phing test
          command: build/bin/phing -f build/phing/build.xml run-tests
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
